-- Update Kitaplar table
ALTER TABLE Kitaplar
ADD COLUMN IF NOT EXISTS Baslik VARCHAR(100) NOT NULL,
ADD COLUMN IF NOT EXISTS Yazar VARCHAR(100) NOT NULL,
ADD COLUMN IF NOT EXISTS Yayin_Yili INT,
ADD COLUMN IF NOT EXISTS Yayin_Evi VARCHAR(100),
ADD COLUMN IF NOT EXISTS ISBN VARCHAR(13) NOT NULL,
ADD COLUMN IF NOT EXISTS Kategori_ID INT,
ADD COLUMN IF NOT EXISTS Stok_Adedi INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS Aciklama VARCHAR(500),
ADD COLUMN IF NOT EXISTS Durum VARCHAR(20) NOT NULL DEFAULT 'Müsait',
ADD COLUMN IF NOT EXISTS Fiyat DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS Eklenme_Tarihi DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- Update Odunc_Almalar table
ALTER TABLE Odunc_Almalar
ADD COLUMN IF NOT EXISTS Teslim_Tarihi DATETIME NULL,
ADD COLUMN IF NOT EXISTS Gecikme_Gun INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS Ceza_Miktari DECIMAL(18,2) NOT NULL DEFAULT 0;

-- Add foreign key constraints if they don't exist
ALTER TABLE Kitaplar
ADD CONSTRAINT FK_Kitaplar_Kategoriler
FOREIGN KEY (Kategori_ID) REFERENCES Kategoriler(Kategori_ID)
ON DELETE SET NULL;

ALTER TABLE Odunc_Almalar
ADD CONSTRAINT FK_Odunc_Almalar_Kitaplar
FOREIGN KEY (Kitap_ID) REFERENCES Kitaplar(Kitap_ID)
ON DELETE RESTRICT;

ALTER TABLE Odunc_Almalar
ADD CONSTRAINT FK_Odunc_Almalar_Kullanicilar
FOREIGN KEY (Kullanici_ID) REFERENCES Kullanicilar(Kullanici_ID)
ON DELETE RESTRICT;

-- Add unique constraints
ALTER TABLE Kitaplar
ADD UNIQUE INDEX IF NOT EXISTS IX_Kitaplar_ISBN (ISBN);

ALTER TABLE Kullanicilar
ADD UNIQUE INDEX IF NOT EXISTS IX_Kullanicilar_Email (Email); 